# ================================================================
# Kokoro-Mamba Pro PEFT 项目 - 最终配置文件
# ================================================================
# 存放于项目根目录 kokoro/config.yaml

# --- 1. 路径配置 (Paths) ---
paths:
  repo_id: "hexgrad/Kokoro-82M-v1.1-zh"
  # 以下路径相对于项目根目录 (kokoro/)
  aishell3_tar: "./train.tar.gz" 
  aishell3_content: "./AISHELL-3/train/content.txt"
  processed_data: "./AISHELL-3-processed"
  output_dir: "./kokoro_finetuned_model_4070L"
  load_mamba_from: null

# --- 2. 数据处理配置 (Data Processing) ---
data:
  sampling_ratio: 1.0
  target_sample_rate: 24000

# --- 3. 训练配置 (Training) ---
training:
  # 4070 Laptop 8G 显存的保守设置
  batch_size: 4
  epochs: 50
  learning_rate: 1e-4
  use_amp: true
  save_every_n_epochs: 5
  num_workers: 4

# --- 4. Mamba 模型配置 (Mamba Model) ---
mamba:
  d_state: 16
  d_conv: 4
  expand: 2
